/* Required skill stations. Classroom values are intentionally identified as fictional.
   Progress uses the course's retention-controlled record, not a second storage system. */
(() => {
  "use strict";
  const course = window.RiggingCourse, core = window.RiggingTrainingCore;
  if (!course || !core) return;
  const $ = s => document.querySelector(s);
  const pair = (en, es) => [en, es];
  const tr = value => Array.isArray(value) ? value[document.documentElement.lang.startsWith("es") ? 1 : 0] : value;
  const esc = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const fnv = value => { let h=0x811c9dc5; for(const c of value){h^=c.charCodeAt(0);h=Math.imul(h,0x01000193)>>>0;}return h.toString(16).padStart(8,"0"); };
  const p = (en, es) => `<p>${tr(pair(en,es))}</p>`;
  const table = (headers, rows) => `<div class="practice-table-wrap"><table><thead><tr>${headers.map(x=>`<th scope="col">${tr(x)}</th>`).join("")}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${tr(x)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;
  const num = (id,label,target,tolerance,hint) => ({id,label,target,tolerance,hint,type:"number"});
  const choice = (id,label,options,hash,hint) => ({id,label,options,hash,hint,type:"choice"});
  const supported = pair("Use only the supplied classroom documents. These values are exercise assumptions, not equipment ratings or field measurements.","Use solo los documentos del aula. Estos valores son supuestos del ejercicio, no capacidades de equipo ni mediciones de campo.");
  const source = pair("Basis: Crane and Rigging Brain — IPT Section 1; Rigging Worksheet, Version 2; component inspection references. Numerical job records and tags below are fictional classroom examples.","Base: Crane and Rigging Brain — IPT Sección 1; Hoja de trabajo de aparejos, Versión 2; referencias de inspección. Los registros numéricos y las etiquetas siguientes son ejemplos ficticios del aula.");
  const symmetry = pair("Model: rigid load; two picks at equal elevation; hook above known CG; static equilibrium; negligible sling and connector weight. Distances use one unit.","Modelo: carga rígida; dos puntos a igual altura; gancho sobre CG conocido; equilibrio estático; peso de eslingas y conectores despreciable. Distancias en una misma unidad.");
  function tagDocument(damaged=false) {
    return `<div class="practice-tag"><span class="document-label">${tr(pair("CLASSROOM TAG • FICTIONAL • NOT FOR EQUIPMENT","ETIQUETA DE AULA • FICTICIA • NO USAR EN EQUIPO"))}</span><h4>CQ-T04</h4>${p("Training specimen • polyester web • 2 in wide • 10 ft long • ID W-104","Muestra de capacitación • faja de poliéster • ancho 2 pulg • longitud 10 pies • ID W-104")}${table([pair("Configuration","Configuración"),pair("Supplied WLL (lb)","WLL suministrado (lb)")],[[pair("Vertical","Vertical"),"6,000"],[pair("Choker, within supplied choke limits","Ahorcado, dentro de límites suministrados"),damaged?pair("UNREADABLE","ILEGIBLE"):"4,800"],[pair("Basket, both legs vertical","Canasta, ambos ramales verticales"),"12,000"],[pair("Basket, 60° from horizontal","Canasta, 60° desde horizontal"),"10,392"]])}${p("Classroom instruction T04: the listed basket row already includes its angle. Permitted choke angle ≥120°. Contact, containment and protection still require separate checks.","Instrucción de aula T04: la fila de canasta ya incluye su ángulo. Ángulo de ahorcamiento permitido ≥120°. Contacto, contención y protección requieren verificaciones separadas.")}</div>`;
  }
  function beamTable(){return table([pair("Span","Separación"),pair("Upper angle","Ángulo superior"),pair("Permitted payload","Carga útil permitida")],[["10 ft","60°","12,000 lb"],["10 ft","45°","9,500 lb"],["12 ft","60°","9,000 lb"]]);}
  const lessons = [
    {id:"weight",title:pair("Weight, units & CG","Peso, unidades y CG"),aim:pair("Account for every item once. Put every position on the same drawing datum.","Cuente cada elemento una sola vez. Ubique cada posición desde el mismo origen del dibujo."),
      study:()=>p("Start at the load, then work upward. Lower rigging carries what hangs below it; upper rigging also carries the below-hook device. Crane gross-load accounting follows the crane's own chart and instructions.","Comience en la carga y avance hacia arriba. El aparejo inferior soporta lo que cuelga debajo; el superior también soporta el dispositivo bajo gancho. El cálculo bruto para la grúa sigue su tabla e instrucciones.")+table([pair("Item","Elemento"),pair("Weight","Peso"),pair("CG from left datum","CG desde origen izquierdo")],[[pair("Frame","Bastidor"),"4,000 lb","5 ft"],[pair("Motor","Motor"),"6,000 lb","8 ft"]])+p("Total = 4,000 + 6,000 = 10,000 lb. Combined CG = (4,000 × 5 + 6,000 × 8) ÷ 10,000 = 6.8 ft. A heavier component pulls the combined CG toward itself.","Total = 4,000 + 6,000 = 10,000 lb. CG combinado = (4,000 × 5 + 6,000 × 8) ÷ 10,000 = 6.8 pies. Un componente más pesado desplaza el CG combinado hacia sí mismo.")+p("12 in = 1 ft; 2,000 lb = 1 US short ton; 1,000 kg = 1 metric tonne. A force is expressed in lbf or N; equipment may mark a mass-equivalent rating in lb, kg or tonnes. Match the manufacturer's units; do not mix short tons and tonnes.","12 pulg = 1 pie; 2,000 lb = 1 tonelada corta de EE. UU.; 1,000 kg = 1 tonelada métrica. Una fuerza se expresa en lbf o N; el equipo puede indicar una capacidad equivalente de masa en lb, kg o toneladas. Respete las unidades del fabricante; no mezcle toneladas cortas y métricas.")+p("For an estimated solid block: 24 × 12 × 6 in = 2 × 1 × 0.5 ft = 1 ft³. Multiply volume by a supplied weight density. Density estimates do not verify hidden contents or the actual shipping weight.","Para un bloque sólido estimado: 24 × 12 × 6 pulg = 2 × 1 × 0.5 pies = 1 pie³. Multiplique volumen por densidad de peso suministrada. La densidad estimada no verifica contenidos ocultos ni el peso real de envío."),
      tasks:[
        {id:"weight-1",title:pair("Build the weight ledger","Prepare el registro de peso"),doc:()=>table([pair("Drawing W1 • supplied items","Dibujo W1 • elementos suministrados"),pair("Weight","Peso")],[[pair("Skid frame","Bastidor"),"3,000 lb"],[pair("Motor","Motor"),"5,000 lb"],[pair("Contents (verified in exercise)","Contenido (verificado en ejercicio)"),"400 lb"],[pair("Spreader above the lower slings","Separador sobre las eslingas inferiores"),"600 lb"]]),fields:[num("payload",pair("Payload below the lower slings (lb)","Carga bajo las eslingas inferiores (lb)"),8400,1,pair("Add frame, motor and contents. Do not put beam weight below its own lower connections.","Sume bastidor, motor y contenido. No coloque el peso de la viga debajo de sus conexiones inferiores.")),num("upper",pair("Total supported by the upper pair (lb)","Total soportado por el par superior (lb)"),9000,1,pair("Add the spreader once to the payload.","Sume el separador una vez a la carga.")),num("tons",pair("Upper supported total in US short tons","Total superior en toneladas cortas de EE. UU."),4.5,.01,pair("Divide pounds by 2,000.","Divida las libras entre 2,000."))]},
        {id:"weight-2",title:pair("Find the combined center","Determine el centro combinado"),doc:()=>p("Drawing W2: 3,000 lb frame at x = 5 ft; 7,000 lb motor at x = 8 ft. Positions are from the same left datum. A separate solid block measures 24 × 12 × 6 in; its assumed weight density is 150 lb/ft³.","Dibujo W2: bastidor de 3,000 lb en x = 5 pies; motor de 7,000 lb en x = 8 pies. Posiciones desde el mismo origen izquierdo. Un bloque sólido separado mide 24 × 12 × 6 pulg; densidad de peso supuesta de 150 lb/pie³."),fields:[num("cg",pair("Frame + motor CG from left (ft)","CG de bastidor + motor desde izquierda (pies)"),core.combinedCg([{weight:3000,position:5},{weight:7000,position:8}]).cg,.01,pair("Sum weight × position, then divide by total weight. The CG lies between the two component centers.","Sume peso × posición y divida entre peso total. El CG queda entre los centros de los componentes.")),num("estimate",pair("Separate block's estimated weight (lb)","Peso estimado del bloque separado (lb)"),150,1,pair("Convert each dimension to feet before multiplying volume × weight density.","Convierta cada dimensión a pies antes de multiplicar volumen × densidad de peso.")),choice("estimate-source",pair("How is that block weight classified?","¿Cómo se clasifica el peso del bloque?"),[pair("Verified shipping weight","Peso de envío verificado"),pair("Estimate requiring verification","Estimación que requiere verificación"),pair("Rated capacity","Capacidad nominal")],"ce126aaa",pair("A supplied density and assumed solid geometry produce an estimate, not a verified shipping record.","La densidad y geometría sólida supuestas producen una estimación, no un registro de envío verificado."))]}
      ]},
    {id:"share",title:pair("Load share & sling demand","Reparto y demanda de eslingas"),aim:pair("Find the vertical share first. Then apply each leg's own geometry.","Determine primero la porción vertical. Luego aplique la geometría de cada ramal."),
      study:()=>p(tr(symmetry),tr(symmetry))+p("For 12,000 lb, a 10 ft pick span, CG 6.5 ft from the left pick and 7.5 ft hook rise: left share = 12,000 × 3.5 ÷ 10 = 4,200 lb; right share = 12,000 × 6.5 ÷ 10 = 7,800 lb.","Para 12,000 lb, separación de 10 pies, CG a 6.5 pies del punto izquierdo y altura de 7.5 pies: porción izquierda = 12,000 × 3.5 ÷ 10 = 4,200 lb; derecha = 12,000 × 6.5 ÷ 10 = 7,800 lb.")+p("L = √(H² + reach²). Tension = vertical share × L/H. Left: 4,200 × 9.925/7.5 ≈ 5,558 lb. Right: 7,800 × 8.276/7.5 ≈ 8,608 lb. Check: the vertical shares sum to 12,000 lb; the sling tensions do not need to.","L = √(H² + alcance²). Tensión = porción vertical × L/H. Izquierda: 4,200 × 9.925/7.5 ≈ 5,558 lb. Derecha: 7,800 × 8.276/7.5 ≈ 8,608 lb. Verifique: las porciones verticales suman 12,000 lb; las tensiones no tienen que sumar ese valor.")+p("Four connections do not prove four equal load-carrying legs. Unequal lengths, elevations and stiffness need a justified load-sharing model. Stop when the supplied information cannot establish it.","Cuatro conexiones no prueban cuatro ramales con reparto igual. Longitudes, elevaciones y rigidez desiguales requieren un modelo justificado. Deténgase cuando la información no permita establecerlo."),
      tasks:[0,1].map(index=>{
        const w=index?15000:10000, cg=index?3:6, h=index?8:6;
        const r=core.solveTwoPoint({totalLoad:w,span:10,cgFromLeft:cg,hookHeight:h});
        return {id:`share-${index+1}`,title:index?pair("Transfer to the other end","Aplique al otro extremo"):pair("Offset machinery skid","Patín con carga desplazada"),doc:()=>p(tr(symmetry),tr(symmetry))+p(`Drawing S${index+1}: supported load ${w.toLocaleString("en-US")} lb; span 10 ft; CG ${cg} ft from left; hook rise ${h} ft. Predict the greater vertical share before calculating.`,`Dibujo S${index+1}: carga ${w.toLocaleString("en-US")} lb; separación 10 pies; CG a ${cg} pies desde izquierda; altura ${h} pies. Prediga la mayor porción vertical antes de calcular.`),fields:[num("left-share",pair("Left vertical share (lb)","Porción vertical izquierda (lb)"),r.legs.left.verticalShare,1,pair("Use the distance from CG to the opposite, right pick: W × (span − x)/span.","Use la distancia del CG al punto opuesto derecho: W × (separación − x)/separación.")),num("right-share",pair("Right vertical share (lb)","Porción vertical derecha (lb)"),r.legs.right.verticalShare,1,pair("Use W × x/span. Check that both shares sum to W.","Use W × x/separación. Verifique que ambas porciones sumen W.")),num("left-tension",pair("Left sling tension (lb)","Tensión izquierda (lb)"),r.legs.left.tension,3,pair("Left length is √(rise² + x²). Multiply left share by length/rise.","La longitud izquierda es √(altura² + x²). Multiplique la porción izquierda por longitud/altura.")),num("right-tension",pair("Right sling tension (lb)","Tensión derecha (lb)"),r.legs.right.tension,3,pair("Use the right leg's own reach and vertical share. Do not reuse the left angle.","Use el alcance y la porción propios del ramal derecho. No reutilice el ángulo izquierdo."))]};})},
    {id:"angle",title:pair("Angles & capacity decisions","Ángulos y capacidad"),aim:pair("Recognize the angle reference. Connect geometry to the applicable rating.","Reconozca la referencia angular. Relacione la geometría con la capacidad aplicable."),
      study:()=>p("θ is measured from horizontal. The angle from vertical is 90° − θ. For a symmetric pair, the included angle is 180° − 2θ. Example: θ = 60° means 30° from vertical and 60° included.","θ se mide desde la horizontal. Desde la vertical es 90° − θ. Para un par simétrico, el ángulo incluido es 180° − 2θ. Ejemplo: θ = 60° equivale a 30° desde vertical y 60° incluido.")+p("Use degree mode. L/H = 1/sin θ. A 10 ft sling with 8 ft rise has L/H = 1.25; 4,000 lb vertical share produces 5,000 lb tension. At 60°, 45° and 30°, a symmetric 10,000 lb load produces about 5,774, 7,071 and 10,000 lb per leg.","Use modo grados. L/H = 1/sen θ. Una eslinga de 10 pies con altura de 8 pies tiene L/H = 1.25; una porción de 4,000 lb produce 5,000 lb de tensión. A 60°, 45° y 30°, una carga simétrica de 10,000 lb produce aproximadamente 5,774, 7,071 y 10,000 lb por ramal.")+p("Demand/WLL is utilization. Use the rating for the exact application. WLL is the permitted rating under specified conditions; design factor is not extra usable capacity. An employer's escalation threshold is a policy trigger, not a manufacturer's rating. Spare capacity does not authorize shock loading.","Demanda/WLL es utilización. Use la capacidad de la aplicación exacta. WLL es la capacidad permitida bajo condiciones indicadas; el factor de diseño no es capacidad adicional utilizable. Un umbral del empleador es una regla de escalamiento, no una capacidad del fabricante. La capacidad disponible no autoriza cargas de choque."),
      tasks:[
        {id:"angle-1",title:pair("Measure, then multiply","Mida y luego multiplique"),doc:()=>p("Drawing A1: two equal legs support a centered 8,000 lb load. Each leg is 10 ft long with 8 ft vertical rise. The entered WLL of each leg for this application is 6,000 lb.","Dibujo A1: dos ramales iguales soportan una carga centrada de 8,000 lb. Cada ramal mide 10 pies con altura de 8 pies. WLL ingresado de cada ramal para esta aplicación: 6,000 lb."),fields:[num("factor",pair("L/H factor","Factor L/H"),1.25,.005,pair("Divide sling length by vertical rise, using the same units.","Divida longitud de eslinga entre altura vertical, en las mismas unidades.")),num("tension",pair("Each leg's tension (lb)","Tensión por ramal (lb)"),5000,1,pair("Determine the symmetric vertical share, then multiply by L/H.","Determine la porción vertical simétrica y multiplíquela por L/H.")),num("use",pair("Each leg's utilization (%)","Utilización por ramal (%)"),5000/6000*100,.1,pair("Divide demand by the applicable WLL and multiply by 100.","Divida demanda entre WLL aplicable y multiplique por 100."))]},
        {id:"angle-2",title:pair("New angle, new demand","Nuevo ángulo, nueva demanda"),doc:()=>p("Drawing A2: centered 9,000 lb load; two equal legs; 60° from horizontal. Candidate leg WLL = 5,000 lb for this exact application. Ignore rigging self-weight in this exercise.","Dibujo A2: carga centrada de 9,000 lb; dos ramales iguales; 60° desde horizontal. WLL candidato = 5,000 lb por ramal para esta aplicación. Omita peso del aparejo en este ejercicio."),fields:[num("vertical-angle",pair("Angle from vertical (degrees)","Ángulo desde vertical (grados)"),30,.1,pair("Horizontal and vertical are 90° apart.","La horizontal y vertical están separadas por 90°.")),num("included",pair("Included angle between legs (degrees)","Ángulo incluido entre ramales (grados)"),60,.1,pair("For a symmetric pair use 180° − 2θ, where θ is from horizontal.","Para un par simétrico use 180° − 2θ; θ se mide desde horizontal.")),num("demand",pair("Tension per leg (lb)","Tensión por ramal (lb)"),4500/Math.sin(Math.PI/3),3,pair("Divide 4,500 by sin(60°); do not multiply by sin.","Divida 4,500 entre sen(60°); no multiplique por sen.")),choice("angle-call",pair("Candidate sling decision","Decisión sobre eslinga candidata"),[pair("Use it: the load is shared","Usarla: la carga se reparte"),pair("Stop: demand exceeds its applicable WLL","Detener: la demanda excede el WLL aplicable"),pair("Use the design factor as reserve","Usar el factor de diseño como reserva")],"1099be5e",pair("Compare each leg's calculated demand to 5,000 lb. A rating cannot be rounded upward.","Compare la demanda por ramal con 5,000 lb. No redondee la capacidad hacia arriba."))]}
      ]},
    {id:"tags",title:pair("Read the tag & select","Lea la etiqueta y seleccione"),aim:pair("Find the applicable row. Explain what the rating does and does not cover.","Encuentre la fila aplicable. Explique qué cubre la capacidad."),
      study:()=>tagDocument()+p("Read identification, material, length, units and configuration before selecting. The 60° basket row already includes that angle: do not reduce it a second time. A tag's rated capacity does not establish containment, edge protection, fit or inspection condition.","Lea identificación, material, longitud, unidades y configuración antes de seleccionar. La fila de canasta a 60° ya incluye ese ángulo: no la reduzca otra vez. La capacidad de la etiqueta no establece contención, protección de bordes, ajuste ni condición de inspección.")+p("For side-loaded hardware, identify the exact product, pin type, size, direction and current application sheet. Distinguish percent capacity remaining from percent reduction. Never transfer one product's angle table to every shackle.","Para herrajes con carga lateral, identifique producto, tipo de perno, tamaño, dirección e instrucciones vigentes. Distinga porcentaje restante de porcentaje de reducción. No aplique una tabla de un producto a todos los grilletes."),
      tasks:[
        {id:"tags-1",title:pair("Use the correct basket row","Use la fila correcta de canasta"),doc:()=>tagDocument()+p("Job T1: one controlled basket supports 9,000 lb with two symmetric legs at 60° from horizontal. Assume documented containment, bearing, protection and condition are acceptable. Evaluate the supplied tag only.","Trabajo T1: una canasta controlada soporta 9,000 lb con dos ramales simétricos a 60° desde horizontal. Suponga contención, apoyo, protección y condición documentados como aceptables. Evalúe solo la etiqueta suministrada."),fields:[num("basket-rating",pair("Applicable basket WLL (lb)","WLL de canasta aplicable (lb)"),10392,1,pair("Read the 60° basket row, not the vertical or vertical-legged basket row.","Lea la fila de canasta a 60°, no vertical ni canasta con ramales verticales.")),num("basket-use",pair("Basket utilization (%)","Utilización de canasta (%)"),9000/10392*100,.1,pair("Compare total basket load with the already angle-rated basket capacity.","Compare la carga total de canasta con su capacidad que ya incluye el ángulo.")),choice("tag-call",pair("What remains true?","¿Qué sigue siendo cierto?"),[pair("The tag alone approves the lift","La etiqueta sola aprueba el izaje"),pair("Apply the angle factor a second time","Aplicar otra vez el factor angular"),pair("This numeric check fits; the complete plan still governs","La comparación numérica cumple; rige el plan completo")],"0dd269be",pair("A capacity comparison is one part of the complete application decision.","La comparación de capacidad es una parte de la decisión completa."))]},
        {id:"tags-2",title:pair("Unreadable information","Información ilegible"),doc:()=>tagDocument(true)+p("Job T2 needs a choker. No replacement identification or governing manufacturer record is available. Do not infer the missing value from another row.","Trabajo T2 requiere ahorcado. No hay identificación de reemplazo ni registro aplicable del fabricante. No deduzca el valor faltante de otra fila."),fields:[choice("tag-missing",pair("Equipment disposition","Disposición del equipo"),[pair("Use the vertical WLL","Usar WLL vertical"),pair("Use a remembered percentage","Usar un porcentaje memorizado"),pair("Withhold use; resolve identification through the authorized process","No usar; resolver identificación mediante proceso autorizado")],"e395a23e",pair("The required rating is not available. Other rows cannot establish it.","La capacidad requerida no está disponible. Otras filas no la establecen.")),choice("tag-evidence",pair("Which information is missing?","¿Qué información falta?"),[pair("The applicable choker rating","La capacidad de ahorcado aplicable"),pair("The specimen length","La longitud de la muestra"),pair("The material","El material")],"b300e0dd",pair("Locate the unreadable configuration row on the supplied document.","Ubique la fila de configuración ilegible en el documento."))]}
      ]},
    {id:"inspection",title:pair("Inspect, measure & decide","Inspeccione, mida y decida"),aim:pair("Name the evidence and the applicable criterion before choosing the disposition.","Nombre la evidencia y el criterio aplicable antes de elegir la disposición."),
      study:()=>p("Inspect the entire sling and every fitting: identification, body, eyes, connections and contact areas. Check before use each shift and as necessary during use. The equipment type, manufacturer criteria, application and inspection interval govern.","Inspeccione toda la eslinga y cada accesorio: identificación, cuerpo, ojos, conexiones y contactos. Revise antes de usar cada turno y cuando sea necesario durante el uso. Rigen tipo de equipo, criterios del fabricante, aplicación e intervalo de inspección.")+p("Wire-rope sling limits are not automatically crane running-rope limits. Web slings and roundslings have different constructions. Identify the actual equipment before selecting a criterion. A clear defect requires removal and segregation; uncertainty requires withholding use until resolved. A photograph alone cannot prove a full inspection.","Los límites de eslingas de cable no son automáticamente límites del cable de operación de grúa. Fajas y eslingas redondas tienen construcciones distintas. Identifique el equipo antes de elegir criterio. Un defecto claro exige retiro y segregación; la incertidumbre exige no usar hasta resolverla. Una foto sola no prueba una inspección completa.")+p("Measurement example: original 1.00 in; current 0.88 in. Loss = (1.00 − 0.88)/1.00 × 100 = 12%. Compare with the criterion for that exact component. Do not apply a generic wear percentage to every item.","Ejemplo: original 1.00 pulg; actual 0.88 pulg. Pérdida = (1.00 − 0.88)/1.00 × 100 = 12%. Compare con el criterio del componente exacto. No aplique un porcentaje genérico a todo equipo.")+p("At the practical station, point to the defect, show how the measurement was taken, identify the reference, segregate the item if required, and record follow-up. The instructor observes each learner individually.","En la estación práctica, señale el defecto, muestre la medición, identifique referencia, segregue si corresponde y registre seguimiento. El instructor observa a cada participante."),
      tasks:[]},
    {id:"spreader",title:pair("Spreader forces & headroom","Fuerzas del separador y altura"),aim:pair("Follow the load upward. Separate lower tension, upper tension and compression.","Siga la carga hacia arriba. Separe tensión inferior, superior y compresión."),
      study:()=>p("A conventional spreader has upper slings at its ends and carries mainly compression. A conventional lifting beam with a central top pick carries bending. Use the device only in its marked configuration; the names do not make the devices interchangeable.","Un separador convencional tiene eslingas superiores en extremos y soporta principalmente compresión. Una viga de izaje convencional con punto superior central soporta flexión. Use el dispositivo en su configuración marcada; los nombres no los hacen intercambiables.")+`<div id="spreaderExplore"></div>`+p("Classroom model: level, symmetric beam, vertical lower lines, equal upper angles and centered payload. Beam weight is represented as equal equivalent end loads. Static forces only; sling/connector weight is omitted. This model does not check buckling, welds, connections, deflection or structural capacity.","Modelo de aula: viga nivelada y simétrica, líneas inferiores verticales, ángulos superiores iguales y carga centrada. Peso de viga representado como cargas equivalentes iguales en extremos. Fuerzas estáticas; se omite peso de eslingas/conectores. No verifica pandeo, soldaduras, conexiones, deflexión ni capacidad estructural.")+p("Example: 10,000 lb payload + 1,000 lb beam = 11,000 lb above the beam. Lower leg = 5,000 lb. Upper vertical share V = 5,500 lb. At θ = 60°: upper T = V/sin θ ≈ 6,351 lb; compression C = V/tan θ ≈ 3,175 lb. The opposing end forces create C, not 2C.","Ejemplo: carga de 10,000 lb + viga de 1,000 lb = 11,000 lb sobre la viga. Ramal inferior = 5,000 lb. Porción vertical superior V = 5,500 lb. A θ = 60°: T superior = V/sen θ ≈ 6,351 lb; compresión C = V/tan θ ≈ 3,175 lb. Las fuerzas opuestas generan C, no 2C.")+p("For span S: rise = (S/2)tan θ; upper sling length = (S/2)/cos θ. Add actual connection clearances. For offset loads or unequal lower forces, determine the complete assembly CG and actual upper geometry; require an approved configuration. Multi-spreader systems and lifting-beam structural design require advanced analysis.","Para separación S: altura = (S/2)tan θ; longitud superior = (S/2)/cos θ. Añada holguras reales. Para cargas descentradas o fuerzas inferiores desiguales, determine CG del conjunto y geometría superior real; exija configuración aprobada. Sistemas múltiples y diseño estructural de vigas requieren análisis avanzado."),
      tasks:[
        {id:"spreader-1",title:pair("Calculate every force","Calcule cada fuerza"),doc:()=>p("Drawing B1: centered payload 8,000 lb; symmetric spreader 800 lb; upper attachment spacing 10 ft; equal upper angles 60° from horizontal; vertical lower lines. Use the stated classroom model.","Dibujo B1: carga centrada de 8,000 lb; separador simétrico de 800 lb; separación superior 10 pies; ángulos superiores iguales de 60° desde horizontal; líneas inferiores verticales. Use el modelo del aula."),fields: (()=>{const r=core.solveSpreader({payload:8000,beamWeight:800,span:10,angle:60});return [num("lower",pair("Each lower sling (lb)","Cada eslinga inferior (lb)"),r.lowerTension,1,pair("The vertical lower pair supports the payload, not the beam above it.","El par inferior vertical soporta la carga, no la viga encima.")),num("upper",pair("Each upper sling tension (lb)","Tensión por eslinga superior (lb)"),r.upperTension,3,pair("Include beam weight; divide by two, then by sin θ.","Incluya peso de viga; divida entre dos y luego entre sen θ.")),num("compression",pair("Ideal axial compression (lb)","Compresión axial ideal (lb)"),r.compression,3,pair("C = upper vertical share / tan θ. Do not add opposing end forces together.","C = porción vertical superior / tan θ. No sume las fuerzas opuestas.")),num("rise",pair("Upper rigging rise (ft)","Altura del aparejo superior (pies)"),r.rise,.02,pair("Rise = half the attachment spacing × tan θ.","Altura = mitad de separación × tan θ."))];})()},
        {id:"spreader-2",title:pair("Select a permitted configuration","Seleccione configuración permitida"),doc:()=>p("Classroom certificate B2 (fictional, not a product rating): payload limit excludes beam self-weight, which is already allowed for in this exercise table. Equal upper slings, vertical lowers, minimum upper angle 45°. Proposed payload 10,000 lb, span 10 ft, available upper rise 9 ft. Reserve an additional 0.25 ft for connections.","Certificado de aula B2 (ficticio, no capacidad de producto): límite de carga útil excluye peso de viga, ya previsto en esta tabla del ejercicio. Eslingas superiores iguales, inferiores verticales, ángulo superior mínimo 45°. Carga propuesta 10,000 lb, separación 10 pies, altura superior disponible 9 pies. Reserve 0.25 pies adicionales para conexiones.")+beamTable(),fields:[choice("beam-selection",pair("Which listed configuration fits the supplied evidence?","¿Qué configuración listada cumple la evidencia?"),[pair("10 ft / 45°","10 pies / 45°"),pair("10 ft / 60°","10 pies / 60°"),pair("10 ft / 30° (not listed)","10 pies / 30° (no listada)")],"6222c488",pair("Check both payload limit and rise plus 0.25 ft. A mathematically possible angle may be prohibited.","Revise límite de carga y altura más 0.25 pies. Un ángulo matemáticamente posible puede estar prohibido.")),choice("beam-change",pair("What if the payload CG moves off center?","¿Qué sucede si el CG de carga se desplaza?"),[pair("Keep equal upper forces","Mantener fuerzas superiores iguales"),pair("Use the beam's largest printed capacity","Usar la mayor capacidad impresa"),pair("Recalculate assembly CG and unequal forces; verify an approved configuration","Recalcular CG y fuerzas desiguales; verificar configuración aprobada")],"6194ed39",pair("The symmetric model depends on centered loading and equal geometry.","El modelo simétrico depende de carga centrada y geometría igual."))]}
      ]},
    {id:"application",title:pair("Defend a complete job plan","Defienda un plan completo"),aim:pair("Carry the numbers, inspection evidence and changing conditions into a field briefing.","Lleve cálculos, evidencia de inspección y condiciones cambiantes a la reunión de campo."),
      study:()=>p("Read the whole packet before choosing gear: drawing and weight source, CG and picks, geometry/headroom, tagged candidates, condition, protection, route, communication and landing. A changed input requires a new decision at every affected step.","Lea el paquete completo antes de elegir equipo: dibujo y fuente de peso, CG y puntos, geometría/altura, candidatos etiquetados, condición, protección, ruta, comunicación y descarga. Un dato cambiado exige nueva decisión en cada paso afectado.")+p("Brief in this order: verified load and CG; individual force and applicable rating; inspection disposition; connection and protection; trial-lift hold and stop signal; controlled travel; stable landing before release. Explain unknowns instead of filling them with guesses.","Informe en este orden: carga y CG verificados; fuerza individual y capacidad aplicable; inspección; conexión y protección; pausa de prueba y señal de alto; traslado controlado; apoyo estable antes de soltar. Explique incógnitas en lugar de adivinarlas."),tasks:[]}
  ];

  const dispositions=[pair("Continue within the supplied inspection record","Continuar según el registro suministrado"),pair("Remove and segregate from service","Retirar y segregar del servicio"),pair("Withhold use pending qualified evaluation","No usar hasta evaluación calificada")];
  const inspectionCases=[
    {id:"inspect-wire",name:pair("Wire-rope sling • WR-21","Eslinga de cable • WR-21"),doc:pair("The complete pre-use record identifies WR-21 and acceptable fittings. At mid-body the strands are displaced outward and the core protrudes. The supplied criterion calls for removal for this distortion. This is a sling, not a crane running rope.","El registro completo identifica WR-21 y accesorios aceptables. En medio del cuerpo los torones están desplazados hacia afuera y el alma sobresale. El criterio suministrado exige retiro por esa deformación. Es una eslinga, no cable de operación de grúa."),hash:"773c28d2",reasonOptions:[pair("Missing capacity units","Faltan unidades de capacidad"),pair("Structural rope distortion","Deformación estructural del cable"),pair("Routine color variation","Variación normal de color")],reasonHash:"7f35e6ea"},
    {id:"inspect-web",name:pair("Polyester web sling • WS-08","Eslinga de faja • WS-08"),doc:pair("Record WS-08 documents a full-length and both-eye inspection, legible identification, no cuts, damaged stitches, heat or chemical damage, and acceptable fittings. The approved load contact and protection match the identified application. No unresolved condition is recorded.","Registro WS-08 documenta inspección completa y de ambos ojos, identificación legible, sin cortes, costuras dañadas, daño térmico o químico y accesorios aceptables. Contacto y protección aprobados coinciden con aplicación identificada. No hay condiciones pendientes."),hash:"9ad0f616",reasonOptions:[pair("A complete supplied record meets the applicable checks","Registro completo cumple verificaciones aplicables"),pair("All web slings are always acceptable","Toda faja es siempre aceptable"),pair("One photograph proves the condition","Una foto prueba la condición")],reasonHash:"71055d54"},
    {id:"inspect-round",name:pair("Roundsling • RS-11","Eslinga redonda • RS-11"),doc:pair("RS-11 has a cover opening with exposed load-bearing core yarn. Identification is legible. The supplied roundsling criterion requires removal for exposed core yarn; a cover patch is not an authorized return-to-service process.","RS-11 tiene abertura en cubierta con hilo portante del alma expuesto. Identificación legible. El criterio exige retiro por alma expuesta; un parche no autoriza retorno al servicio."),hash:"481e21c3",reasonOptions:[pair("Illegible identification","Identificación ilegible"),pair("Too many sling legs","Demasiados ramales"),pair("Exposed load-bearing core yarn","Hilo portante del alma expuesto")],reasonHash:"e0037d88"},
    {id:"inspect-chain",name:pair("Alloy chain sling • CH-17","Eslinga de cadena • CH-17"),doc:pair("A link's bearing area measures 0.43 in. The original size, grade and matching wear table are unavailable. The record does not establish acceptance or a specific rejection threshold. Keep the sling out of use while those facts are resolved.","El apoyo de un eslabón mide 0.43 pulg. No están disponibles tamaño original, grado ni tabla de desgaste correspondiente. El registro no establece aceptación ni límite específico. Mantenga la eslinga sin uso mientras se resuelven esos datos."),hash:"4e991f2f",reasonOptions:[pair("The exact size/grade and governing wear limit are missing","Faltan tamaño/grado exactos y límite de desgaste"),pair("0.43 in is always acceptable","0.43 pulg es siempre aceptable"),pair("The color determines chain strength","El color determina resistencia")],reasonHash:"1811202d"},
    {id:"inspect-hardware",name:pair("Shackle • SH-04","Grillete • SH-04"),doc:pair("SH-04's original specified bow section is 1.00 in; the documented minimum current section is 0.88 in. The supplied criterion for this exact classroom component requires removal at 10% dimensional loss. Matching original pin and identification are present.","Sección original de arco SH-04: 1.00 pulg; sección mínima actual documentada: 0.88 pulg. El criterio para este componente del aula exige retiro al 10% de pérdida dimensional. Perno original correspondiente e identificación presentes."),hash:"676cc3c7",reasonOptions:[pair("Missing pin","Perno faltante"),pair("Measured loss reaches the supplied removal criterion","Pérdida medida alcanza criterio de retiro"),pair("The bow is too heavy","Arco demasiado pesado")],reasonHash:"bfb2ede5",measure:true},
    {id:"inspect-beam",name:pair("Below-hook device • BD-06","Dispositivo bajo gancho • BD-06"),doc:pair("BD-06's log shows current identification, correct assembled configuration, completed required inspection and no defects. Today's operator sees a line beside a weld that cannot be distinguished from a crack using available evidence. A prior acceptable inspection does not resolve today's uncertain indication.","El registro BD-06 muestra identificación vigente, configuración correcta, inspección requerida completa y sin defectos. Hoy se observa una línea junto a soldadura que no se distingue de una grieta con la evidencia disponible. La inspección anterior no resuelve la indicación incierta de hoy."),hash:"66d4dd25",reasonOptions:[pair("The previous log overrides today's indication","El registro previo anula la indicación de hoy"),pair("The line can be ignored below WLL","Se puede ignorar por debajo del WLL"),pair("Today's uncertain weld indication needs evaluation before use","La indicación incierta requiere evaluación antes de usar")],reasonHash:"65e2086d"}
  ];
  lessons.find(x=>x.id==="inspection").tasks=inspectionCases.map(c=>({id:c.id,title:c.name,doc:()=>p(tr(c.doc),tr(c.doc)),fields:[...(c.measure?[num("loss",pair("Section loss (%)","Pérdida de sección (%)"),12,.1,pair("(Original − current) ÷ original × 100. Use the original dimension as denominator.","(Original − actual) ÷ original × 100. Use la dimensión original como denominador."))]:[]),choice(c.id,pair("Disposition for this record","Disposición para este registro"),dispositions,c.hash,pair("Match the supplied evidence to the applicable criterion. Unresolved evidence is not acceptance.","Compare evidencia con criterio aplicable. Evidencia pendiente no significa aceptación.")),choice(c.id+"-evidence",pair("State the controlling evidence","Indique evidencia determinante"),c.reasonOptions,c.reasonHash,pair("Name the actual documented observation or missing fact, not a generic rule.","Nombre observación documentada o dato faltante, no una regla genérica."))]}));

  const jobs=[
    {id:"job-skid",title:pair("Motor replacement","Reemplazo de motor"),doc:pair("Job J1: the signed 8,200 lb skid drawing was issued before a heavier motor was installed. Four lugs are present, but the plan uses two sling legs. The new assembly weight and CG have not been established.","Trabajo J1: dibujo firmado de patín de 8,200 lb emitido antes de instalar motor más pesado. Hay cuatro orejas pero el plan usa dos ramales. No se han establecido peso y CG nuevos."),options:[pair("Proceed using the signed old drawing","Proceder con dibujo firmado anterior"),pair("Hold; establish current weight/CG and recalculate each affected demand","Pausar; establecer peso/CG actuales y recalcular demandas"),pair("Divide old weight by four lugs","Dividir peso anterior entre cuatro orejas")],hash:"fe88ba85",reason:pair("The installed configuration changed after the drawing was issued.","La configuración instalada cambió después de emitirse el dibujo.")},
    {id:"job-pipe",title:pair("Pipe bundle containment","Contención de paquete de tubos"),doc:pair("Job J2: bundle weight and CG are supplied. The sling capacity is sufficient. The proposed wrap is not covered by the supplied manufacturer's instructions, and longitudinal restraint is unresolved.","Trabajo J2: peso y CG suministrados. Capacidad de eslinga suficiente. La vuelta propuesta no está cubierta por instrucciones suministradas y la restricción longitudinal sigue sin resolver."),options:[pair("Capacity is enough; proceed slowly","Capacidad suficiente; proceder lentamente"),pair("Add wraps until the bundle feels tight","Añadir vueltas hasta sentir ajuste"),pair("Hold; obtain an approved arrangement and resolve sliding/containment","Pausar; obtener arreglo aprobado y resolver deslizamiento/contención")],hash:"3727127b",reason:pair("Capacity does not establish containment or manufacturer permission.","Capacidad no establece contención ni permiso del fabricante.")},
    {id:"job-edge",title:pair("Protection moves","La protección se mueve"),doc:pair("Job J3: the inspected web sling and identified capacity fit the sharp-edged plate plan. During taking slack, one protector moves away from the corner. No damage assessment has yet been made.","Trabajo J3: eslinga de faja inspeccionada y capacidad coinciden con plan para placa filosa. Al tomar holgura, un protector se desplaza de la esquina. Aún no se evalúa daño."),options:[pair("Stop and safely remove tension; inspect, correct protection and reverify","Detener y quitar tensión con seguridad; inspeccionar, corregir protección y verificar"),pair("Push the pad back by hand under tension","Empujar protector con mano bajo tensión"),pair("Finish because the sling is below WLL","Terminar porque está bajo WLL")],hash:"1b67f950",reason:pair("The contact protection changed at the point of loading.","La protección de contacto cambió al aplicar carga.")},
    {id:"job-frame",title:pair("Headroom changes","Cambia la altura libre"),doc:pair("Job J4: the approved spreader arrangement requires 8.9 ft upper headroom including connections. A newly installed obstruction leaves 7 ft. The plan offers no approved lower-angle alternative.","Trabajo J4: arreglo aprobado de separador requiere 8.9 pies de altura superior incluyendo conexiones. Obstáculo nuevo deja 7 pies. El plan no ofrece alternativa aprobada de menor ángulo."),options:[pair("Flatten the upper legs without recalculation","Aplanar ramales sin recalcular"),pair("Hold and obtain a revised, verified configuration","Pausar y obtener configuración revisada y verificada"),pair("Use the spreader as a center-picked lifting beam","Usar separador como viga con punto central")],hash:"b1fe0691",reason:pair("Available headroom no longer fits the approved geometry.","Altura disponible ya no cumple geometría aprobada.")},
    {id:"job-four",title:pair("Four picks, uneven legs","Cuatro puntos, ramales desiguales"),doc:pair("Job J5: a rigid frame has four lugs at unequal elevations, and one sling leg is shorter. No equalizing arrangement or validated load-sharing analysis is supplied.","Trabajo J5: bastidor rígido con cuatro orejas a alturas distintas y un ramal más corto. No se proporciona igualación ni análisis validado de reparto."),options:[pair("Every leg takes exactly 25%","Cada ramal toma exactamente 25%"),pair("A larger hook makes the shares equal","Gancho mayor iguala porciones"),pair("Require a justified model for the actual geometry before selection","Exigir modelo justificado de geometría real antes de seleccionar")],hash:"b2b2d4d3",reason:pair("Leg count alone does not determine the effective load share.","Número de ramales solo no determina reparto efectivo.")},
    {id:"job-landing",title:pair("Complete the lift briefing","Complete la reunión del izaje"),doc:pair("Job J6: load information, calculations, identified ratings, inspections, connections and protection are verified for the exercise. Route is clear and access controlled. Blocking is positioned on a verified supporting surface. Establish the first movement and landing sequence.","Trabajo J6: datos de carga, cálculos, capacidades, inspecciones, conexiones y protección verificados en ejercicio. Ruta despejada y acceso controlado. Bloqueo colocado en superficie verificada. Establezca secuencia inicial y descarga."),options:[pair("Take slack with hook over CG; hold at the trial lift, verify seating/balance/communication; land stably before releasing tension","Tomar holgura con gancho sobre CG; pausar prueba, verificar asiento/equilibrio/comunicación; apoyar estable antes de liberar tensión"),pair("Travel continuously and check balance after landing","Trasladar continuamente y revisar equilibrio al descargar"),pair("Use hands beneath the load to place blocking","Usar manos bajo carga para colocar bloqueo")],hash:"4926dca4",reason:pair("The first movement and stable landing are verification hold points, with hands clear and an agreed stop signal.","El movimiento inicial y apoyo estable son puntos de verificación, con manos fuera y señal de alto acordada.")}
  ];
  lessons.find(x=>x.id==="application").tasks=jobs.map(j=>({id:j.id,title:j.title,doc:()=>p(tr(j.doc),tr(j.doc)),fields:[choice(j.id,pair("Your field decision","Su decisión de campo"),j.options,j.hash,j.reason),choice(j.id+"-reason",pair("What must the briefing communicate?","¿Qué debe comunicar la reunión?"),[j.reason,pair("Proceed whenever the largest component is rated high enough","Proceder cuando el componente mayor tenga capacidad suficiente"),pair("The photograph is sufficient evidence","La fotografía es evidencia suficiente")],({"job-skid":"72acaaa9","job-pipe":"adc73b64","job-edge":"dd8d30fb","job-frame":"abc4e60d","job-four":"bf8c54dc","job-landing":"d5821587"})[j.id],pair("Use the specific change or hold point described in the packet.","Use el cambio o punto de pausa específico descrito en el paquete."))]}));

  const navNames=[pair("Weight & CG","Peso y CG"),pair("Load share","Reparto de carga"),pair("Angles","Ángulos"),pair("Tags & ratings","Etiquetas y capacidad"),pair("Inspection","Inspección"),pair("Spreaders","Separadores"),pair("Job applications","Aplicaciones")];
  const allTasks=lessons.flatMap(l=>l.tasks);
  let state=course.read("skillStationsV1",{passed:{},events:[],drafts:{},help:{}});
  if(!state||typeof state!=="object"||!state.passed||!Array.isArray(state.events))state={passed:{},events:[],drafts:{},help:{}};
  state.drafts ||= {}; state.help ||= {};
  let selected=lessons[0].id,mode="study",taskIndex=0,feedback=null,beamAngle=60;
  const lesson=()=>lessons.find(l=>l.id===selected);
  const task=()=>lesson().tasks[taskIndex];
  const count=()=>allTasks.filter(t=>state.passed[t.id]).length;
  const complete=()=>count()===allTasks.length;
  function save(){course.write("skillStationsV1",state);course.refresh();}
  const section=document.createElement("section");section.id="practiceLab";section.className="practice-lab";section.setAttribute("aria-labelledby","practiceTitle");
  $("main").appendChild(section);
  const roadmap=document.createElement("nav");roadmap.className="practice-roadmap";roadmap.setAttribute("aria-label",tr(pair("Learning route","Ruta de aprendizaje")));
  $("#learnerJourney").insertAdjacentElement("beforebegin",roadmap);
  function open(id){id ||= lessons.find(l=>l.tasks.some(t=>!state.passed[t.id]))?.id || selected;if(lessons.some(l=>l.id===id)){selected=id;taskIndex=0;feedback=null;}render();course.openTool("practice");requestAnimationFrame(()=>$("#practiceTitle")?.focus({preventScroll:true}));}
  function render(){
    const l=lesson();
    section.innerHTML=`<header class="practice-head"><span class="practice-kicker">${tr(pair("LEARN → WORK IT OUT → DEFEND YOUR CALL","APRENDA → CALCULE → DEFIENDA SU DECISIÓN"))}</span><h2 id="practiceTitle" tabindex="-1">${tr(pair("Build your rigging skills","Desarrolle sus habilidades de aparejos"))}</h2><p>${tr(pair("Seven required stations. Study an example, then solve a different case. Your record keeps independent work, retries and coaching separate.","Siete estaciones obligatorias. Estudie un ejemplo y resuelva otro caso. Su registro distingue trabajo independiente, reintentos y ayuda."))}</p></header><div class="practice-layout"><nav class="practice-nav" aria-label="${tr(pair("Skill stations","Estaciones de habilidades"))}">${lessons.map((x,i)=>`<button type="button" data-station="${x.id}" aria-current="${x.id===selected?"step":"false"}"><b>${i+1}. ${tr(navNames[i])}</b><small>${x.tasks.filter(t=>state.passed[t.id]).length} / ${x.tasks.length} ${tr(pair("checks complete","verificaciones completas"))}</small></button>`).join("")}</nav><article class="practice-content"><span class="practice-kicker" style="color:#526983">${tr(pair("Station","Estación"))} ${lessons.indexOf(l)+1} / ${lessons.length}</span><h3>${tr(l.title)}</h3><p>${tr(l.aim)}</p><div class="practice-modes" role="tablist" aria-label="${tr(pair("Learning mode","Modo de aprendizaje"))}"><button type="button" role="tab" aria-selected="${mode==="study"}" data-mode="study">${tr(pair("1 · Walkthrough","1 · Ejemplo guiado"))}</button><button type="button" role="tab" aria-selected="${mode==="solve"}" data-mode="solve">${tr(pair("2 · Your turn","2 · Su turno"))}</button></div>${mode==="study"?l.study()+`<div class="practice-actions"><button type="button" class="primary" data-mode="solve">${tr(pair("Try a different case →","Intente otro caso →"))}</button></div>`:renderTask()}<p class="practice-source">${tr(source)} <a href="https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.251" target="_blank" rel="noopener">OSHA 1926.251</a> · <a href="https://www.modulift.com/2023/07/04/how-to-safely-assemble-a-spreader-beam/" target="_blank" rel="noopener">${tr(pair("Manufacturer assembly guidance","Guía de armado del fabricante"))}</a></p></article></div>`;
    section.querySelectorAll("[data-station]").forEach(b=>b.onclick=()=>{selected=b.dataset.station;taskIndex=0;mode="study";feedback=null;render();});
    section.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;feedback=null;render();});
    section.querySelectorAll("[data-task]").forEach(b=>b.onclick=()=>{taskIndex=Number(b.dataset.task);feedback=null;render();});
    $("#practiceForm")?.addEventListener("input",capture);
    $("#practiceForm")?.addEventListener("change",capture);
    $("#practiceForm")?.addEventListener("submit",check);
    $("#practiceHint")?.addEventListener("click",()=>{state.help[task().id]=true;save();feedback={hint:true};render();});
    $("#practiceNext")?.addEventListener("click",()=>{if(taskIndex<l.tasks.length-1){taskIndex++;}else{const i=lessons.indexOf(l);if(i<lessons.length-1){selected=lessons[i+1].id;taskIndex=0;mode="study";}else{course.openTool("mastery");return;}}feedback=null;render();});
    if(selected==="spreader"&&mode==="study")renderBeam();
    const nav=section.querySelector(".practice-nav"),active=nav.querySelector('[aria-current="step"]');
    if(nav.scrollWidth>nav.clientWidth)nav.scrollLeft=Math.max(0,active.offsetLeft-nav.offsetLeft-12);
    section.querySelectorAll('[role="tablist"]').forEach(list=>list.addEventListener("keydown",event=>{
      if(!["ArrowLeft","ArrowRight","Home","End"].includes(event.key))return;
      const tabs=[...list.querySelectorAll('[role="tab"]')],i=tabs.indexOf(document.activeElement);if(i<0)return;
      event.preventDefault();const next=event.key==="Home"?0:event.key==="End"?tabs.length-1:(i+(event.key==="ArrowRight"?1:-1)+tabs.length)%tabs.length;
      const attr=tabs[next].hasAttribute("data-mode")?"data-mode":"data-task",value=tabs[next].getAttribute(attr);tabs[next].click();section.querySelector(`[role="tab"][${attr}="${value}"]`)?.focus({preventScroll:true});
    }));
    sync();
  }
  function capture(){const data=new FormData($("#practiceForm"));state.drafts[task().id]=Object.fromEntries(data);course.write("skillStationsV1",state);}
  function renderTask(){
    const t=task(),draft=state.drafts[t.id]||{},passed=state.passed[t.id];
    return `<div class="practice-tasks" role="tablist" aria-label="${tr(pair("Practice cases","Casos de práctica"))}">${lesson().tasks.map((x,i)=>`<button type="button" role="tab" aria-selected="${i===taskIndex}" data-task="${i}">${state.passed[x.id]?"✓ ":""}${tr(pair("Case","Caso"))} ${i+1}</button>`).join("")}</div><h4>${tr(t.title)}</h4><div class="practice-document"><span class="document-label">${tr(pair("SUPPLIED CLASSROOM JOB RECORD","REGISTRO DE TRABAJO SUMINISTRADO EN AULA"))}</span>${t.doc()}<p class="practice-assumptions">${tr(supported)}</p></div><form id="practiceForm" data-case="${t.id}"><div class="practice-form">${t.fields.map(f=>`<label class="practice-field" for="field-${f.id}"><span>${tr(f.label)}</span>${f.type==="number"?`<input id="field-${f.id}" name="${f.id}" type="number" inputmode="decimal" step="any" required value="${esc(draft[f.id]||"")}" ${passed?"readonly":""}>`:`<select id="field-${f.id}" name="${f.id}" required ${passed?"disabled":""}><option value="">${tr(pair("Choose using the evidence","Elija según la evidencia"))}</option>${f.options.map((o,i)=>`<option value="${i}" ${String(draft[f.id])===String(i)?"selected":""}>${tr(o)}</option>`).join("")}</select>`}${f.type==="number"?`<small>${tr(pair("Enter a number without commas. Keep precision until the final result.","Ingrese número sin separadores de miles. Mantenga precisión hasta el resultado final."))}</small>`:""}</label>`).join("")}</div><div class="practice-actions"><button type="submit" class="primary" ${passed?"disabled":""}>${tr(pair("Check my work","Verificar mi trabajo"))}</button><button id="practiceHint" type="button" ${passed?"disabled":""}>${tr(pair("Coach me","Orientarme"))}</button>${passed?`<button type="button" id="practiceNext">${tr(pair("Continue →","Continuar →"))}</button>`:""}</div></form><div id="practiceFeedback" class="practice-feedback ${feedback?.good||passed?"good":feedback?.errors?"bad":""}" role="status" aria-live="polite">${feedback?.hint?`<b>${tr(pair("Coaching used for this case","Ayuda usada para este caso"))}</b><ul>${t.fields.map(f=>`<li>${tr(f.hint)}</li>`).join("")}</ul>`:feedback?.errors?`<b>${tr(pair("Recheck these steps","Revise estos pasos"))}</b><ul>${feedback.errors.map(f=>`<li><b>${tr(f.label)}:</b> ${tr(f.hint)}</li>`).join("")}</ul>`:passed?`<b>${tr(pair("Evidence check complete","Verificación de evidencia completa"))}</b> · ${passed.help?tr(pair("With coaching","Con ayuda")):passed.attempts===1?tr(pair("Independent first attempt","Primer intento independiente")):tr(pair(`Corrected after ${passed.attempts} attempts`,`Corregido tras ${passed.attempts} intentos`))}${p("Carry this reasoning into the next case. Field performance still requires observation.","Aplique este razonamiento al siguiente caso. El desempeño en campo aún requiere observación.")}`:""}</div>`;
  }
  function check(event){
    event.preventDefault();if(state.passed[task().id])return;capture();const t=task(),draft=state.drafts[t.id];
    const fields=t.fields.map(f=>({id:f.id,correct:f.type==="number"?core.numericAnswer(draft[f.id],f.target,f.tolerance):fnv(`RIGLAB3:${f.id}:${draft[f.id]}`)===f.hash}));
    const errors=t.fields.filter(f=>!fields.find(x=>x.id===f.id).correct);
    const eventRecord={case:t.id,skill:selected,at:new Date().toISOString(),correct:!errors.length,help:Boolean(state.help[t.id]),fields};state.events.push(eventRecord);
    if(!errors.length)state.passed[t.id]={at:eventRecord.at,attempts:state.events.filter(e=>e.case===t.id).length,help:eventRecord.help};
    feedback=errors.length?{errors}:{good:true};save();render();
    errors.forEach(f=>$("#field-"+f.id)?.setAttribute("aria-invalid","true"));$("#practiceFeedback")?.scrollIntoView({behavior:"smooth",block:"nearest"});
  }
  let beamView = "assembly";
  function renderBeam(){
    const host=$("#spreaderExplore");if(!host)return;
    const r=core.solveSpreader({payload:10000,beamWeight:1000,span:10,angle:beamAngle});
    const scale=Math.min(38,170/r.rise),x=350-5*scale,y=270,h=y-r.rise*scale;
    host.innerHTML=`<label class="practice-field" for="beamAngle"><span>${tr(pair("Compare upper angle from horizontal","Compare ángulo superior desde horizontal"))}: <output>${beamAngle}°</output></span><input id="beamAngle" type="range" min="30" max="75" step="5" value="${beamAngle}"></label><svg class="practice-diagram" viewBox="0 0 700 440" role="img" aria-label="${tr(pair("Symmetric spreader force model, geometry to scale","Modelo simétrico de fuerzas, geometría a escala"))}"><path d="M${x} ${y} L350 ${h} L${700-x} ${y}" fill="none" stroke="#e7cd82" stroke-width="6"/><path d="M${x} ${y} V365 M${700-x} ${y} V365" stroke="#7fd1c2" stroke-width="5"/><rect x="${x}" y="${y-7}" width="${10*scale}" height="14" fill="#769bbf"/><rect x="${x-20}" y="365" width="${10*scale+40}" height="28" fill="#456383"/><text x="350" y="32" text-anchor="middle" fill="white" font-size="17">${tr(pair("Payload 10,000 lb • beam 1,000 lb","Carga 10,000 lb • viga 1,000 lb"))}</text><text x="350" y="420" text-anchor="middle" fill="white" font-size="17">${tr(pair("Lower slings: 5,000 lb each","Eslingas inferiores: 5,000 lb cada una"))}</text></svg>${table([pair("Upper tension / leg","Tensión superior / ramal"),pair("Compression","Compresión"),pair("Rise","Altura")],[[`${Math.round(r.upperTension).toLocaleString()} lb`,`${Math.round(r.compression).toLocaleString()} lb`,`${r.rise.toFixed(2)} ft`]])}<div class="practice-tip">${beamAngle<45?tr(pair("MATHEMATICAL COMPARISON ONLY. The classroom certificate requires at least 45°. This setting is not a permitted configuration.","SOLO COMPARACIÓN MATEMÁTICA. El certificado del aula exige mínimo 45°. Esta configuración no está permitida.")):tr(pair("Less headroom increases upper tension and compression. Forces alone do not establish the device rating; use the applicable configuration table.","Menor altura aumenta tensión superior y compresión. Las fuerzas solas no establecen capacidad; use la tabla de configuración aplicable."))}</div>`;
    host.dataset.view=beamView;
    host.insertAdjacentHTML("afterbegin",`<div class="beam-view-controls" role="group" aria-label="${tr(pair("Spreader view","Vista del separador"))}"><button type="button" data-beam-view="assembly" aria-pressed="${beamView==="assembly"}">${tr(pair("3D assembly","Conjunto 3D"))}</button><button type="button" data-beam-view="diagram" aria-pressed="${beamView==="diagram"}">${tr(pair("Force diagram","Diagrama de fuerzas"))}</button></div>`);
    host.querySelector(".practice-diagram").insertAdjacentHTML("beforebegin",`<figure class="beam-assembly"><img src="assets/blender/spreader-${beamAngle}.webp" width="1000" height="850" alt="${tr(pair(`Blender classroom model at ${beamAngle} degrees: gold upper slings meet above a blue spreader, teal lower slings hang vertically to a centered load, orange arrows point inward along the bar.`,`Modelo de aula Blender a ${beamAngle} grados: eslingas superiores doradas sobre un separador azul, eslingas inferiores verdes verticales a una carga centrada y flechas naranjas hacia dentro de la barra.`))}"><figcaption><strong>${tr(pair("Trace the load upward","Siga la carga hacia arriba"))}</strong><span>${tr(pair("Teal: lower tension · Gold: upper tension · Orange: inward compression","Verde: tensión inferior · Dorado: tensión superior · Naranja: compresión hacia dentro"))}</span><span>${tr(pair("Illustrative 3D model. Attachment centers follow the selected geometry; connection shapes are symbolic. Perspective changes the apparent angle—use the force diagram to read geometry. Camera framing adjusts to fit.","Modelo 3D ilustrativo. Los centros de conexión siguen la geometría seleccionada; las conexiones son simbólicas. La perspectiva cambia el ángulo aparente: use el diagrama para leer la geometría. El encuadre se ajusta al conjunto."))}</span></figcaption></figure>`);
    const assemblyImage=host.querySelector(".beam-assembly img");
    assemblyImage.onerror=()=>{
      host.dataset.view="diagram";
      host.querySelectorAll("[data-beam-view]").forEach(button=>button.setAttribute("aria-pressed",String(button.dataset.beamView==="diagram")));
      if(!host.querySelector(".beam-image-status"))host.querySelector(".beam-view-controls").insertAdjacentHTML("afterend",`<p class="beam-image-status" role="status">${tr(pair("The 3D image is unavailable. The force diagram and calculations are still available. Select 3D assembly to retry when connected.","La imagen 3D no está disponible. El diagrama de fuerzas y los cálculos siguen disponibles. Seleccione Conjunto 3D para reintentar cuando tenga conexión."))}</p>`);
    };
    host.querySelectorAll("[data-beam-view]").forEach(button=>button.onclick=()=>{beamView=button.dataset.beamView;renderBeam();host.querySelector(`[data-beam-view="${beamView}"]`).focus({preventScroll:true});});
    $("#beamAngle").oninput=e=>{beamAngle=Number(e.target.value);renderBeam();$("#beamAngle").focus({preventScroll:true});};
  }
  function journey(index){
    let box=$("#journeyPractice");if(!box){box=document.createElement("div");box.id="journeyPractice";box.className="journey-practice";$("#journeyFeedback")?.insertAdjacentElement("afterend",box);}
    const map=["weight","tags","share","angle","inspection","application"],id=map[index]||"weight";
    box.innerHTML=`<p>${tr(pair("Put this decision into practice. Required skill stations turn the explanation into work you can demonstrate.","Ponga esta decisión en práctica. Las estaciones obligatorias convierten la explicación en trabajo demostrable."))}</p><button type="button">${tr(lessons.find(l=>l.id===id).title)} →</button>`;box.querySelector("button").onclick=()=>open(id);
  }
  function sync(){
    roadmap.innerHTML=`<button type="button" data-route="learn"><span>01</span><b>${tr(pair("Understand the six decisions","Comprenda las seis decisiones"))}</b><span>${tr(pair("Follow the load from the drawing to the landing.","Siga la carga desde el dibujo hasta la descarga."))}</span></button><button type="button" data-route="practice"><span>02</span><b>${tr(pair("Work through the skill stations","Complete las estaciones"))}</b><span>${count()} / ${allTasks.length} ${tr(pair("evidence checks complete","verificaciones completas"))}</span></button><button type="button" data-route="mastery"><span>03</span><b>${tr(pair("Demonstrate your knowledge","Demuestre sus conocimientos"))}</b><span>${tr(pair("Complete the final check and review your evidence.","Complete evaluación final y revise su evidencia."))}</span></button>`;
    roadmap.querySelectorAll("[data-route]").forEach(b=>b.onclick=()=>b.dataset.route==="learn"?$("#heroGuided").click():b.dataset.route==="practice"?open():course.openTool("mastery"));
    let gate=$("#practiceGate");if(!gate){gate=document.createElement("div");gate.id="practiceGate";gate.className="practice-gate";$("#completionCard")?.insertAdjacentElement("beforebegin",gate);}
    gate.innerHTML=`<p><b>${tr(pair("Required skill evidence","Evidencia obligatoria de habilidades"))}: ${count()} / ${allTasks.length}.</b> ${complete()?tr(pair("All skill checks are complete. The six decisions and final knowledge check are also required.","Todas las verificaciones completas. También se requieren seis decisiones y evaluación final.")):tr(pair("Course completion requires these stations as well as the six decisions and final knowledge check.","Completar el curso requiere estas estaciones, además de seis decisiones y evaluación final."))}</p><button type="button">${tr(pair("Continue skill practice →","Continuar práctica →"))}</button>`;
    gate.querySelector("button").onclick=()=>open(lessons.find(l=>l.tasks.some(t=>!state.passed[t.id]))?.id||"weight");
  }
  window.RiggingPractice={open,complete,sync,journey,tagDocument,record:()=>({version:1,completed:count(),required:allTasks.length,passed:state.passed,events:state.events}),
    summary:()=>`${tr(pair("Required skill checks","Verificaciones obligatorias"))}: ${count()} / ${allTasks.length}; ${tr(pair("field performance not observed","desempeño en campo no observado"))}`,
    reset:()=>{state={passed:{},events:[],drafts:{},help:{}};feedback=null;taskIndex=0;mode="study";render();}};
  $("#langToggle")?.addEventListener("click",()=>setTimeout(()=>{render();journey(course.currentStep());},0));
  render();journey(course.currentStep());course.refresh();
})();
