/* Fictional classroom records. These values are not equipment ratings. */
(function(root, factory) {
  const api = factory(typeof module === 'object' && module.exports ? require('./rigging-core.js') : root.RiggingTrainingCore);
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.RiggingSkills = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function(core) {
  'use strict';
  const VERSION = '2026.09.13.1';
  const pair = (en, es) => ({ en, es });
  const numeric = (id, en, es, expected, hintEn, hintEs, tolerance = 0.5) =>
    ({ id, label: pair(en, es), expected, hint: pair(hintEn, hintEs), tolerance });
  const choice = (id, en, es, options, expected, hintEn, hintEs) =>
    ({ id, label: pair(en, es), options: options.map(([value,en,es]) => ({ value, label:pair(en,es) })), expected, hint:pair(hintEn,hintEs) });
  const calls = [['continue','Continue the classroom review','Continuar la revisión de aula'],['hold','Hold for missing information or correction','Suspender por información faltante o corrección'],['remove','Remove and isolate the item','Retirar y aislar el elemento']];
  const disposition = (expected, hintEn, hintEs) => choice('call','Disposition','Disposición',calls,expected,hintEn,hintEs);
  const cases = [];
  const add = (id, station, titleEn, titleEs, docEn, docEs, fields) => cases.push({ id,station,title:pair(titleEn,titleEs),document:pair(docEn,docEs),fields });
  add('weight-total','weight','Shipping record A','Registro de envío A',
    'Machine: 6,400 lb. Base: 850 lb. Attached contents: 350 lb. Rigging below the hook: 420 lb. The machine weight excludes the other listed items. Establish both the supported payload and the total hook load.',
    'Máquina: 6,400 lb. Base: 850 lb. Contenido unido: 350 lb. Aparejo debajo del gancho: 420 lb. El peso de la máquina excluye los demás elementos. Determine la carga útil y la carga total del gancho.',
    [numeric('payload','Supported payload (lb)','Carga útil soportada (lb)',7600,'Add the machine, base and contents once.','Sume una vez la máquina, la base y el contenido.'),numeric('hook','Total hook load (lb)','Carga total del gancho (lb)',8020,'Include the rigging below the hook.','Incluya el aparejo debajo del gancho.')]);
  add('weight-units','weight','Units before arithmetic','Unidades antes de calcular',
    'A packing list states 3.6 US short tons. Use 1 US short ton = 2,000 lb and 1 lb = 0.45359237 kg. A metric tonne is a different unit.',
    'Una lista indica 3.6 toneladas cortas de EE. UU. Use 1 tonelada corta = 2,000 lb y 1 lb = 0.45359237 kg. La tonelada métrica es otra unidad.',
    [numeric('pounds','Weight (lb)','Peso (lb)',7200,'Multiply US short tons by 2,000.','Multiplique las toneladas cortas por 2,000.'),numeric('kg','Mass equivalent (kg)','Equivalente de masa (kg)',7200*0.45359237,'Convert the pounds using the supplied factor.','Convierta las libras con el factor suministrado.',1)]);
  const cg = core.combinedCG([{weight:3000,position:24},{weight:5000,position:84}]);
  add('weight-cg','weight','Combined center of gravity','Centro de gravedad combinado',
    'Two attached items share a left-hand datum: 3,000 lb at x = 24 in and 5,000 lb at x = 84 in. Positions are horizontal distances from the same datum. Find total moment before dividing by total weight.',
    'Dos elementos unidos comparten un origen a la izquierda: 3,000 lb en x = 24 pulg y 5,000 lb en x = 84 pulg. Las posiciones son distancias horizontales desde el mismo origen. Obtenga el momento total antes de dividir por el peso total.',
    [numeric('moment','Total moment (lb·in)','Momento total (lb·pulg)',cg.moment,'Sum weight × position for both items.','Sume peso × posición de ambos elementos.'),numeric('cg','Combined CG from datum (in)','CG combinado desde el origen (pulg)',cg.position,'Divide total moment by combined weight.','Divida el momento total por el peso combinado.',0.1)]);
  const share = core.solveTwoPoint({totalLoad:15000,span:144,cgFromLeft:54,hookHeight:96});
  add('share-reactions','share','Offset machinery skid','Patín de maquinaria descentrado',
    'Rigid payload: 15,000 lb. Picks are level, 144 in apart. CG is 54 in from the left pick and 90 in from the right. Hook is vertically above the CG. Find the two vertical support shares; do not use sling tension yet.',
    'Carga rígida: 15,000 lb. Puntos al mismo nivel, separados 144 pulg. CG a 54 pulg del punto izquierdo y 90 pulg del derecho. Gancho verticalmente sobre el CG. Obtenga las dos porciones verticales; todavía no use la tensión de las eslingas.',
    [numeric('left','Left support share (lb)','Porción izquierda (lb)',share.legs.left.verticalShare,'The left support uses the distance from CG to the right pick.','El apoyo izquierdo usa la distancia del CG al punto derecho.'),numeric('right','Right support share (lb)','Porción derecha (lb)',share.legs.right.verticalShare,'The two vertical shares must sum to the payload.','Las dos porciones verticales deben sumar la carga útil.')]);
  add('share-geometry','share','Each leg has its own geometry','Cada ramal tiene su geometría',
    'Use the 15,000 lb skid, 144 in span and CG 54 in from the left. Hook rise above the picks is 96 in. Left share = 9,375 lb; right share = 5,625 lb. Calculate each straight leg length and then its tension using L/H.',
    'Use el patín de 15,000 lb, separación de 144 pulg y CG a 54 pulg del punto izquierdo. Altura del gancho sobre los puntos: 96 pulg. Porción izquierda = 9,375 lb; derecha = 5,625 lb. Calcule cada longitud recta y después su tensión usando L/H.',
    [numeric('lengthL','Left length (in)','Longitud izquierda (pulg)',share.geometry.leftLength,'Use √(96² + 54²).','Use √(96² + 54²).',0.1),numeric('lengthR','Right length (in)','Longitud derecha (pulg)',share.geometry.rightLength,'Use the right horizontal reach of 90 in.','Use el alcance horizontal derecho de 90 pulg.',0.1),numeric('tensionL','Left tension (lb)','Tensión izquierda (lb)',share.legs.left.tension,'Multiply the left vertical share by left L/96.','Multiplique la porción izquierda por L izquierda/96.',15),numeric('tensionR','Right tension (lb)','Tensión derecha (lb)',share.legs.right.tension,'Use the right share and right leg length.','Use la porción y la longitud del ramal derecho.',15)]);
  const angleT = 8400/2/Math.sin(Math.PI/3);
  add('angle-demand','angles','Balanced bridle at 60°','Brida equilibrada a 60°',
    'Centered rigid load: 8,400 lb. Two equal sling legs, each 60° from horizontal. Each leg carries half the vertical load. Derive the angle factor and leg tension.',
    'Carga rígida centrada: 8,400 lb. Dos ramales iguales, cada uno a 60° desde la horizontal. Cada ramal soporta la mitad de la carga vertical. Obtenga el factor de ángulo y la tensión.',
    [numeric('factor','Angle factor (L/H)','Factor de ángulo (L/H)',1/Math.sin(Math.PI/3),'Use 1 ÷ sin(60°), not the included angle.','Use 1 ÷ sen(60°), no el ángulo incluido.',0.002),numeric('tension','Each leg tension (lb)','Tensión de cada ramal (lb)',angleT,'Multiply one vertical share by the angle factor.','Multiplique una porción vertical por el factor de ángulo.',10)]);
  add('angle-capacity','angles','Demand and utilization','Demanda y utilización',
    'A calculated leg tension is 6,250 lb. Classroom sling A has 6,000 lb allowable axial tension under the stated conditions; sling B has 8,000 lb. Both records match the planned material, fittings, temperature and geometry. Other component checks remain separate.',
    'La tensión calculada es 6,250 lb. La eslinga de aula A permite 6,000 lb de tensión axial bajo las condiciones indicadas; B permite 8,000 lb. Ambos registros coinciden con el material, terminales, temperatura y geometría previstos. Los demás componentes requieren verificaciones separadas.',
    [numeric('util','Sling B utilization (%)','Utilización de B (%)',78.125,'Utilization = demand ÷ applicable capacity × 100.','Utilización = demanda ÷ capacidad aplicable × 100.',0.1),choice('sling','Capacity selection for this leg','Selección de capacidad del ramal',[['A','A · 6,000 lb','A · 6,000 lb'],['B','B · 8,000 lb','B · 8,000 lb'],['either','Either','Cualquiera']],'B','Compare each candidate capacity with the full leg tension.','Compare cada capacidad con la tensión completa del ramal.')]);
  add('tag-rating','tags','Read the planned hitch row','Lea la fila del enganche previsto',
    'CLASSROOM TAG T-17 · Web sling · ID WS-17 · 12 ft. Vertical: 5,000 lb. Choker: 4,000 lb under the supplied conditions. Basket with vertical supporting parts: 10,000 lb; inclined basket ratings are not supplied. Planned lift: single vertical hitch, 4,600 lb, suitable designated point. Tag and condition are legible and documented.',
    'ETIQUETA DE AULA T-17 · Eslinga de faja · ID WS-17 · 12 pies. Vertical: 5,000 lb. Ahorcado: 4,000 lb bajo las condiciones suministradas. Canasta con partes verticales: 10,000 lb; sin capacidades para canasta inclinada. Plan: enganche vertical único, 4,600 lb, punto designado adecuado. Etiqueta y condición legibles y documentadas.',
    [numeric('rating','Applicable rated load (lb)','Carga nominal aplicable (lb)',5000,'Choose the vertical row for the planned vertical hitch.','Elija la fila vertical para el enganche vertical previsto.'),numeric('util','Utilization (%)','Utilización (%)',92,'Compare 4,600 lb with the selected hitch rating.','Compare 4,600 lb con la capacidad del enganche elegido.',0.1)]);
  add('tag-unreadable','tags','An incomplete identity record','Registro de identidad incompleto',
    'Tag T-18: the manufacturer and serial number are unreadable. A nearby sling of the same color is marked 10,000 lb. No record connects that tag or rating to T-18. The proposed load is 2,000 lb.',
    'Etiqueta T-18: fabricante y número de serie ilegibles. Una eslinga cercana del mismo color indica 10,000 lb. Ningún registro vincula esa etiqueta o capacidad con T-18. Carga propuesta: 2,000 lb.',
    [disposition('remove','Missing identification is not repaired by color matching or a lighter load.','La falta de identificación no se resuelve por el color ni por una carga menor.'),choice('basis','Controlling reason','Razón que rige',[['color','Same color establishes capacity','El mismo color establece la capacidad'],['id','Capacity cannot be tied to this item','No se puede vincular la capacidad a este elemento'],['load','A light load needs no identification','Una carga ligera no requiere identificación']],'id','The evidence must identify this exact sling.','La evidencia debe identificar esta eslinga exacta.')]);
  const inspection = [
    ['01','Inspection record 01','Registro de inspección 01','Web sling WS-31: legible identification; planned hitch and load within the supplied rating; full-length inspection finds no cuts, broken stitching, heat damage or other listed removal condition. Connection and edge protection checks are complete.','Eslinga de faja WS-31: identificación legible; enganche y carga dentro de la capacidad suministrada; inspección completa sin cortes, costuras rotas, daño térmico ni otra condición de retiro listada. Conexiones y protección de bordes verificadas.','continue','No listed stop condition appears in this supplied record. Continue only the classroom review.','Este registro no presenta una condición de alto. Continúe solamente la revisión de aula.'],
    ['02','Inspection record 02','Registro de inspección 02','Web sling WS-32: a 12 mm cut crosses load-bearing yarns. Identification is legible. The proposed load is 20% of the marked vertical rating.','Eslinga de faja WS-32: corte de 12 mm que atraviesa hilos portantes. Identificación legible. La carga propuesta equivale al 20% de la capacidad vertical marcada.','remove','A reduced load does not repair cut load-bearing material.','Reducir la carga no repara el material portante cortado.'],
    ['03','Inspection record 03','Registro de inspección 03','Hardware H-03: no visible distortion; measured bearing section is 0.94 in. Original nominal size and applicable manufacturer wear limit are missing. Inspector requests the matching instructions.','Herraje H-03: sin deformación visible; sección de apoyo medida de 0.94 pulg. Faltan tamaño nominal original y límite de desgaste aplicable del fabricante. El inspector solicita las instrucciones correspondientes.','hold','A measured dimension alone is insufficient without its baseline and applicable limit.','La dimensión medida es insuficiente sin su valor original y límite aplicable.'],
    ['04','Inspection record 04','Registro de inspección 04','Shackle SH-04: bow identification is legible. The installed pin came from a different shackle model. Its threads engage. No manufacturer authorization for this combination exists.','Grillete SH-04: identificación del cuerpo legible. El perno proviene de otro modelo. Las roscas acoplan. No existe autorización del fabricante para esta combinación.','remove','Thread engagement does not establish that the pin and bow are a matched assembly.','El acoplamiento de roscas no demuestra compatibilidad entre perno y cuerpo.'],
    ['05','Inspection record 05','Registro de inspección 05','Classroom hardware H-05: nominal section 1.00 in; smallest measured section 0.94 in. THIS FICTIONAL RECORD specifies removal at 5% section loss. The value is only an exercise criterion, not a limit for real hardware.','Herraje de aula H-05: sección nominal 1.00 pulg; sección mínima medida 0.94 pulg. ESTE REGISTRO FICTICIO especifica retiro al 5% de pérdida de sección. Es un criterio de ejercicio, no un límite para herrajes reales.','remove','Compare percentage loss with the criterion printed in this particular record.','Compare la pérdida porcentual con el criterio de este registro específico.'],
    ['06','Inspection record 06','Registro de inspección 06','Wire rope sling WR-06: identification matches the controlled record. Full-length inspection, end fittings and construction-specific wire-break check are documented satisfactory; there is no permanent distortion or other listed removal condition. Planned configuration matches the supplied rating.','Eslinga de cable WR-06: identificación coincidente con el registro controlado. Inspección completa, terminales y verificación de alambres rotos según la construcción documentados como satisfactorios; sin deformación permanente ni otra condición de retiro. Configuración prevista coincidente con la capacidad suministrada.','continue','Judge the supplied findings; a wire rope sling is not automatically defective.','Evalúe los hallazgos suministrados; una eslinga de cable no es defectuosa automáticamente.']
  ];
  inspection.forEach(([id,en,es,de,ds,answer,he,hs]) => add('inspection-'+id,'inspection',en,es,de,ds,
    [...(id==='05'?[numeric('loss','Section loss (%)','Pérdida de sección (%)',6,'Use (original − measured) ÷ original × 100.','Use (original − medido) ÷ original × 100.',0.1)]:[]),disposition(answer,he,hs)]));
  const beam = core.solveSpreader({payload:9000,beamWeight:600,span:120,angle:45});
  add('spreader-config','spreader','Spreader configuration packet','Paquete de configuración del separador',
    'CLASSROOM DEVICE SB-1. Centered payload 9,000 lb; centered beam weight 600 lb; level beam; vertical lower legs. Planned span 120 in, upper sling angle 45° from horizontal, available hook rise above beam 64 in. Configuration A: 120 in span, maximum payload 10,000 lb, minimum upper angle 45°. Configuration B: 144 in span, maximum payload 8,000 lb, minimum upper angle 60°. Upper legs permit 7,000 lb each, lower legs 5,000 lb each, top connection 10,000 lb. Neglect sling self-weight for this exercise only. Select the marked row and calculate demands; these forces do not establish structural capacity.',
    'DISPOSITIVO DE AULA SB-1. Carga útil centrada 9,000 lb; peso centrado de viga 600 lb; viga nivelada; ramales inferiores verticales. Separación prevista 120 pulg, ángulo superior 45° desde la horizontal, altura disponible del gancho sobre la viga 64 pulg. Configuración A: 120 pulg, carga útil máxima 10,000 lb, ángulo superior mínimo 45°. Configuración B: 144 pulg, carga útil máxima 8,000 lb, ángulo mínimo 60°. Ramales superiores permiten 7,000 lb cada uno, inferiores 5,000 lb y conexión superior 10,000 lb. Ignore el peso de las eslingas solo en este ejercicio. Seleccione la fila marcada y calcule demandas; estas fuerzas no establecen capacidad estructural.',
    [numeric('hook','Hook load (lb)','Carga del gancho (lb)',beam.hookLoad,'Include the beam self-weight.','Incluya el peso propio de la viga.'),numeric('lower','Each lower tension (lb)','Tensión inferior por ramal (lb)',beam.lowerTension,'Only the payload is below the lower legs.','Solo la carga útil está debajo de los ramales inferiores.'),numeric('upper','Each upper tension (lb)','Tensión superior por ramal (lb)',beam.upperTension,'Apply 1/sin(45°) to half the hook load.','Aplique 1/sen(45°) a la mitad de la carga del gancho.',10),numeric('compression','Ideal beam compression (lb)','Compresión ideal de la viga (lb)',beam.compression,'Use the horizontal component of one upper-leg tension.','Use el componente horizontal de la tensión de un ramal superior.',10),numeric('rise','Required hook rise above beam (in)','Altura requerida sobre la viga (pulg)',beam.rise,'Use half the span × tan(45°). Compare with 64 in.','Use media separación × tan(45°). Compare con 64 pulg.',0.1),choice('config','Matching configuration','Configuración coincidente',[['A','A · 120 in','A · 120 pulg'],['B','B · 144 in','B · 144 pulg'],['none','Neither row','Ninguna fila']],'A','The row must match span, payload and minimum angle together.','La fila debe cumplir separación, carga útil y ángulo mínimo juntos.')]);
  const apps = [
    ['01','Congested installation','Instalación congestionada','Payload and ratings are verified. A pedestrian route crosses the planned suspended-load path; the exclusion area has not been established. The operator has not started.','Carga y capacidades verificadas. Una ruta peatonal cruza la trayectoria suspendida; no se ha establecido el área de exclusión. El operador no ha comenzado.','hold','route','Control access and the load route before proceeding.','Controle el acceso y la trayectoria antes de continuar.'],
    ['02','Outdoor panel','Panel exterior','The job plan gives a wind hold point of 20 mph for this specific operation. The site instrument reads sustained wind of 23 mph. This is a supplied job-plan limit, not a universal crane wind limit.','El plan fija un punto de suspensión de 20 mph para esta operación específica. El instrumento del sitio indica viento sostenido de 23 mph. Es un límite del plan suministrado, no un límite universal.','hold','limit','Compare the measured condition with this job plan.','Compare la condición medida con este plan.'],
    ['03','Balanced shop skid','Patín equilibrado de taller','The signed classroom packet confirms weight and CG, matching ratings, passed inspection, compatible points, clear route and agreed signals. A trial lift is planned a few inches above support with a stop to verify balance. No listed check is missing.','El paquete de aula firmado confirma peso y CG, capacidades coincidentes, inspección satisfactoria, puntos compatibles, ruta despejada y señales acordadas. Se prevé un izaje de prueba de pocas pulgadas con parada para verificar equilibrio. No falta ninguna verificación listada.','continue','trial','Continue to the stated trial-lift hold point, subject to the authorized crew.','Continúe al punto de verificación del izaje de prueba, sujeto a la cuadrilla autorizada.'],
    ['04','Bundle containment','Contención del paquete','Loose pipe is supported by a basket. No engineered end stop, verified wrap arrangement or other means prevents longitudinal sliding. The sling rating is ample.','Tubería suelta apoyada en canasta. Ningún tope diseñado, arreglo de vueltas verificado u otro medio impide el deslizamiento longitudinal. La capacidad de la eslinga es suficiente.','hold','contain','Capacity alone does not establish load containment.','La capacidad por sí sola no establece la contención.'],
    ['05','Changed geometry','Geometría cambiada','An earlier calculation accepted a 60° bridle. A headroom change produces 30° legs. No one has recalculated the demand or checked the marked angle rating. The weight is unchanged.','Un cálculo anterior aceptó una brida a 60°. Un cambio de altura produce ramales a 30°. Nadie recalculó la demanda ni verificó la capacidad marcada por ángulo. El peso no cambió.','hold','recalculate','Changing the angle invalidates the old tension and capacity comparison.','Cambiar el ángulo invalida la tensión y comparación de capacidad anteriores.'],
    ['06','Trial-lift observation','Observación del izaje de prueba','During the planned first-inch hold, the load remains level, rigging seats as specified, nothing snags and the exclusion area remains clear. The authorized signal person and operator confirm the next planned movement.','Durante la parada inicial prevista, la carga permanece nivelada, el aparejo asienta según lo especificado, no hay enganches y el área sigue despejada. El señalero autorizado y el operador confirman el siguiente movimiento previsto.','continue','observed','Use the documented trial-lift observations and authorized next step.','Use las observaciones documentadas y el siguiente paso autorizado.']
  ];
  const reasons = [ ['route','Uncontrolled access to the load path','Acceso no controlado a la trayectoria'],['limit','A supplied operating limit is exceeded','Se excede un límite operativo suministrado'],['trial','Packet complete; proceed to trial-lift verification','Paquete completo; seguir a verificación de prueba'],['contain','Longitudinal containment is unverified','Contención longitudinal sin verificar'],['recalculate','Geometry changed; recalculate and recheck','Geometría cambiada; recalcular y verificar'],['observed','Trial checks support the authorized next movement','Las verificaciones respaldan el movimiento autorizado'] ];
  apps.forEach(([id,en,es,de,ds,call,reason,he,hs])=>add('application-'+id,'applications',en,es,de,ds,[disposition(call,he,hs),choice('reason','Evidence that controls this decision','Evidencia que rige esta decisión',reasons,reason,he,hs)]));
  const stations = [
    ['weight','Weight, units & CG','Peso, unidades y CG','Example: 2,000 lb at 20 in plus 4,000 lb at 80 in gives 6,000 lb and (40,000 + 320,000) / 6,000 = 60 in CG. Add below-hook equipment separately for hook load.','Ejemplo: 2,000 lb a 20 pulg más 4,000 lb a 80 pulg da 6,000 lb y CG = (40,000 + 320,000) / 6,000 = 60 pulg. Sume aparte el equipo bajo el gancho para su carga.'],
    ['share','Asymmetric support shares','Reparto de apoyos asimétricos','Example: 10,000 lb, 100 in span, CG 40 in from left, rise 80 in. Shares: left 6,000; right 4,000 lb. Left length √(40²+80²) = 89.44 in; tension = 6,000 × 89.44/80 = 6,708 lb. Right length 100 in; tension 5,000 lb.','Ejemplo: 10,000 lb, separación 100 pulg, CG a 40 pulg de la izquierda, altura 80 pulg. Porciones: izquierda 6,000; derecha 4,000 lb. Longitud izquierda √(40²+80²) = 89.44 pulg; tensión = 6,000 × 89.44/80 = 6,708 lb. Longitud derecha 100 pulg; tensión 5,000 lb.'],
    ['angles','Angles & utilization','Ángulos y utilización','Example: 6,000 lb centered at 45° gives 3,000 / sin(45°) = 4,243 lb per leg. A 5,000 lb applicable axial rating yields 84.9% utilization. Do not divide an already angle-rated assembly capacity by the angle factor again.','Ejemplo: 6,000 lb centradas a 45° da 3,000 / sen(45°) = 4,243 lb por ramal. Una capacidad axial aplicable de 5,000 lb da 84.9% de utilización. No vuelva a reducir por ángulo una capacidad de conjunto que ya lo incluye.'],
    ['tags','Identification & selection','Identificación y selección','Example: a fictional tag lists vertical 3,000 lb and choker 2,400 lb. A 2,700 lb vertical lift uses the vertical row (90%). The same load exceeds the choker row. Color and appearance do not establish a rating.','Ejemplo: una etiqueta ficticia indica vertical 3,000 lb y ahorcado 2,400 lb. Un izaje vertical de 2,700 lb usa la fila vertical (90%). Esa carga excede la fila de ahorcado. El color y la apariencia no establecen capacidad.'],
    ['inspection','Six inspection records','Seis registros de inspección','Read condition, identification, measurements and the exact applicable criteria. A sound documented item may continue through review. Missing information creates a hold; a confirmed removal condition requires isolation. Example: original 20 mm, measured 19.6 mm gives 2% loss; a disposition still requires the matching equipment limit.','Lea condición, identificación, medidas y criterios aplicables exactos. Un elemento sano documentado puede seguir en revisión. Información faltante exige suspensión; una condición confirmada de retiro exige aislamiento. Ejemplo: original 20 mm, medido 19.6 mm da pérdida de 2%; la disposición todavía requiere el límite correspondiente.'],
    ['spreader','Spreader forces & configuration','Fuerzas y configuración del separador','Example: payload 6,000 lb plus beam 400 lb, span 96 in, upper angle 60°. Hook = 6,400 lb; each lower leg = 3,000 lb; each upper leg = 3,200/sin(60°) = 3,695 lb; ideal compression = 3,200/tan(60°) = 1,848 lb; rise = 48 tan(60°) = 83.14 in. Beam selection requires the marked configuration and manufacturer instructions.','Ejemplo: carga útil 6,000 lb más viga 400 lb, separación 96 pulg, ángulo superior 60°. Gancho = 6,400 lb; cada ramal inferior = 3,000 lb; superior = 3,200/sen(60°) = 3,695 lb; compresión ideal = 3,200/tan(60°) = 1,848 lb; altura = 48 tan(60°) = 83.14 pulg. La selección requiere configuración marcada e instrucciones del fabricante.'],
    ['applications','Six application packets','Seis paquetes de aplicación','Separate verified facts from unknowns. State the hold, correction or authorized next step and the evidence that controls it. Example: a documented hook rating cannot settle an unknown load weight. Hold until the load is established, then recalculate and review the full system.','Separe los hechos verificados de lo desconocido. Indique suspensión, corrección o siguiente paso autorizado y su evidencia. Ejemplo: la capacidad documentada del gancho no resuelve un peso desconocido. Suspenda hasta establecer la carga, luego recalcule y revise todo el sistema.']
  ].map(([id,en,es,we,ws])=>({id,title:pair(en,es),worked:pair(we,ws)}));
  function grade(item, values) {
    const fields = item.fields.map(field=>{
      const raw=values[field.id];
      const correct = field.options ? raw===field.expected : raw!=='' && raw!==undefined && raw!==null && Number.isFinite(Number(raw)) && Math.abs(Number(raw)-field.expected)<=field.tolerance;
      return {id:field.id,correct,hint:field.hint};
    });
    return {correct:fields.every(f=>f.correct),fields};
  }
  function isMastered(record, item) {
    const row = record?.[item.id];
    const last = Array.isArray(row?.attempts) ? row.attempts.at(-1) : null;
    return row?.version===VERSION && Boolean(last?.correct) && JSON.stringify(last.values)===JSON.stringify(row.draft) && grade(item,row.draft||{}).correct;
  }
  function progress(record) {
    return {total:cases.length, mastered:cases.filter(item=>isMastered(record,item)).length,
      complete:cases.every(item=>isMastered(record,item))};
  }
  return {VERSION,cases,stations,grade,isMastered,progress};
});
